name: Build Windows App

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate Config
        run: |
          echo '{ "BACKEND_URL": "${{ vars.BACKEND_URL }}", "FRONTEND_URL": "${{ vars.FRONTEND_URL }}" }' > config.json

      - name: Build Electron App for Windows
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Bump version and create tag
        id: tag_creation
        run: |
          $VERSION = (node -p "require('./package.json').version")
          "TAG_NAME=v$VERSION" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          echo "Version: $VERSION"
          git tag "v$VERSION"
          git push origin "v$VERSION"

      - name: List dist folder contents
        run: Get-ChildItem -Path dist/ | Format-Table -AutoSize

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.blockmap
            dist/latest.yml
          tag_name: ${{ steps.tag_creation.outputs.TAG_NAME }}
