name: Build MSIX with electron-packager

on:
  push:
    branches: [ windows-store ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Package app (electron-packager)
        run: npm run pack

      - name: Convert to MSIX (electron-windows-store)
        run: npm run msix

      - name: Upload MSIX package
        uses: actions/upload-artifact@v4
        with:
          name: msix-package
          path: store-app/*