name: Build Windows App

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Electron App for Windows
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Bump version and create tag
        run: |
          $VERSION = (node -p "require('./package.json').version")
          echo "TAG_NAME=v$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"
          git tag "v$VERSION"
          git push origin "v$VERSION"

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
          tag_name: $TAG_NAME
